userName=hrm_user
password=Hrm_user@123
url=https://www.syntaxhrm.com/web/index.php/auth/login
browser=Chrome


dbURL =jdbc:mysql://3.88.142.137:3306/hrm

dbUserName =hrm_std

dbPassword =hrm_std@2026

username=Asmaadams
Password=Asmaadams9$

essUser = arundhati123
essPassword = Arundhati@22